sudo: required
language: java
jdk: oraclejdk8

install:
   - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
   - mvn test
deploy:
   provider: script
   script: mvn clean verify
   on:
      branch: master
